name: perso2

networks:
  backend:
    driver: bridge

volumes:
  db:
    name: "perso2_mariadb"

services:
  #
  # Database Service
  #
  mysql:
    image: "mariadb:lts"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - backend
    links:
      - mysql
