import bcrypt from "bcryptjs";
import fs from "fs/promises";
import readline from "readline/promises";
import config from "dotenv";
config.config();

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});
console.log("Please enter your admin key and press enter");
const key = await rl.question("Admin key: ");
rl.close();
let hash = bcrypt.hashSync(
  key.toString().trim(),
  parseInt(process.env.BCRYPT_SALT),
);
hash = hash.replaceAll("$", "\\$");

let message = "\n# This file was generated by generateAdminKey.js\n";
message += "# you can delete previous declaration\n";
message += `ADMIN_KEY=${hash}\n\n`;
const file = await fs.open("./.env", "a");
await file.appendFile(message);
await file.close();
console.log('Admin key added in ".env" file.\n You should check it out....\n');
